import {
  ArrowDown,
  ArrowRight,
  ArrowUpRight,
  Award,
  BadgeCheck,
  BrickWall,
  Briefcase,
  Building2,
  CalendarClock,
  Check,
  CheckCheck,
  ChevronDown,
  ChevronRight,
  ChevronUp,
  ChevronsLeftRight,
  CircleAlert,
  CircleCheckBig,
  ClipboardList,
  Clock,
  Droplets,
  ExternalLink,
  Fence,
  FileText,
  Flower2,
  Grid2x2,
  Handshake,
  HardHat,
  ImageOff,
  Info,
  Leaf,
  LoaderCircle,
  Mail,
  MapPin,
  Menu,
  MessageSquare,
  MoveHorizontal,
  Navigation,
  PencilRuler,
  Phone,
  Printer,
  Quote,
  Recycle,
  Route,
  Scissors,
  Send,
  ShieldCheck,
  Shovel,
  Snowflake,
  Sparkles,
  Sprout,
  Star,
  ThumbsUp,
  TreeDeciduous,
  Trees,
  Truck,
  Umbrella,
  Users,
  WavesHorizontal,
  Wrench,
  X,
} from 'lucide-react';
import type { LucideProps } from 'lucide-react';

/** Zentrale Icon-Sammlung. Keine Emojis, ausschliesslich Strichicons. */
export const icons = {
  ArrowDown,
  ArrowRight,
  ArrowUpRight,
  Award,
  BadgeCheck,
  BrickWall,
  Briefcase,
  Building2,
  CalendarClock,
  Check,
  CheckCheck,
  ChevronDown,
  ChevronRight,
  ChevronUp,
  ChevronsLeftRight,
  CircleAlert,
  CircleCheckBig,
  ClipboardList,
  Clock,
  Droplets,
  ExternalLink,
  Fence,
  FileText,
  Flower2,
  Grid2x2,
  Handshake,
  HardHat,
  ImageOff,
  Info,
  Leaf,
  LoaderCircle,
  Mail,
  MapPin,
  Menu,
  MessageSquare,
  MoveHorizontal,
  Navigation,
  PencilRuler,
  Phone,
  Printer,
  Quote,
  Recycle,
  Route,
  Scissors,
  Send,
  ShieldCheck,
  Shovel,
  Snowflake,
  Sparkles,
  Sprout,
  Star,
  ThumbsUp,
  TreeDeciduous,
  Trees,
  Truck,
  Umbrella,
  Users,
  WavesHorizontal,
  Wrench,
  X,
} as const;

export type IconName = keyof typeof icons;

type IconProps = LucideProps & { name: string };

export default function Icon({ name, ...props }: IconProps) {
  const Component = icons[name as IconName] ?? Leaf;
  return <Component aria-hidden="true" {...props} />;
}
